-- Create Fly table
CREATE TABLE Fly (
                     id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     number VARCHAR2(255) NOT NULL,
                     departure VARCHAR2(255) NOT NULL,
                     arrival VARCHAR2(255) NOT NULL,
                     departureTime TIMESTAMP NOT NULL,
                     arrivalTime TIMESTAMP NOT NULL,
                     numberSeats NUMBER NOT NULL
);

-- Create Ticket table
CREATE TABLE Ticket (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        price VARCHAR2(255) NOT NULL,
                        seat VARCHAR2(2) NOT NULL,
                        fly_id NUMBER,
                        passenger_id NUMBER,
                        CONSTRAINT fk_fly FOREIGN KEY (fly_id) REFERENCES Fly(id),
                        CONSTRAINT fk_passenger FOREIGN KEY (passenger_id) REFERENCES User(id)
);

-- Create User table
CREATE TABLE User (
                      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR2(255) NOT NULL,
                      email VARCHAR2(255) NOT NULL,
                      age NUMBER NOT NULL,
                      phoneNumber VARCHAR2(255) NOT NULL,
                      ticket_id NUMBER
);

-- Procedure to insert initial data
CREATE OR REPLACE PROCEDURE insert_initial_data AS
BEGIN
    -- Insert into Fly table
INSERT INTO Fly (number, departure, arrival, departureTime, arrivalTime, numberSeats) VALUES ('Flight 1', 'City A', 'City B', TO_TIMESTAMP('2023-10-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-10-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 100);
INSERT INTO Fly (number, departure, arrival, departureTime, arrivalTime, numberSeats) VALUES ('Flight 2', 'City C', 'City D', TO_TIMESTAMP('2023-10-02 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2023-10-02 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), 150);

-- Insert into User table
INSERT INTO User (name, email, age, phoneNumber) VALUES ('User 1', 'user1@example.com', 30, '1234567890');
INSERT INTO User (name, email, age, phoneNumber) VALUES ('User 2', 'user2@example.com', 25, '0987654321');
INSERT INTO User (name, email, age, phoneNumber) VALUES ('User 3', 'user3@example.com', 35, '1122334455');
INSERT INTO User (name, email, age, phoneNumber) VALUES ('User 4', 'user4@example.com', 28, '5566778899');
INSERT INTO User (name, email, age, phoneNumber) VALUES ('User 5', 'user5@example.com', 32, '6677889900');
INSERT INTO User (name, email, age, phoneNumber) VALUES ('User 6', 'user6@example.com', 29, '7788990011');
INSERT INTO User (name, email, age, phoneNumber) VALUES ('User 7', 'user7@example.com', 31, '8899001122');
INSERT INTO User (name, email, age, phoneNumber) VALUES ('User 8', 'user8@example.com', 27, '9900112233');
INSERT INTO User (name, email, age, phoneNumber) VALUES ('User 9', 'user9@example.com', 34, '0011223344');
INSERT INTO User (name, email, age, phoneNumber) VALUES ('User 10', 'user10@example.com', 26, '1122334455');
INSERT INTO User (name, email, age, phoneNumber) VALUES ('User 11', 'user11@example.com', 33, '2233445566');
INSERT INTO User (name, email, age, phoneNumber) VALUES ('User 12', 'user12@example.com', 36, '3344556677');

-- Insert into Ticket table
INSERT INTO Ticket (price, seat, fly_id, passenger_id) VALUES ('1000', '1A', 1, 1);
INSERT INTO Ticket (price, seat, fly_id, passenger_id) VALUES ('500', '2B', 1, 2);
INSERT INTO Ticket (price, seat, fly_id, passenger_id) VALUES ('1000', '1A', 2, 3);
INSERT INTO Ticket (price, seat, fly_id, passenger_id) VALUES ('500', '2B', 2, 4);
INSERT INTO Ticket (price, seat, fly_id, passenger_id) VALUES ('1000', '1A', 1, 5);
INSERT INTO Ticket (price, seat, fly_id, passenger_id) VALUES ('500', '2B', 1, 6);
INSERT INTO Ticket (price, seat, fly_id, passenger_id) VALUES ('1000', '1A', 2, 7);
INSERT INTO Ticket (price, seat, fly_id, passenger_id) VALUES ('500', '2B', 2, 8);
INSERT INTO Ticket (price, seat, fly_id, passenger_id) VALUES ('1000', '1A', 1, 9);
INSERT INTO Ticket (price, seat, fly_id, passenger_id) VALUES ('500', '2B', 1, 10);
INSERT INTO Ticket (price, seat, fly_id, passenger_id) VALUES ('1000', '1A', 2, 11);
INSERT INTO Ticket (price, seat, fly_id, passenger_id) VALUES ('500', '2B', 2, 12);
END;
/

-- Execute the procedure to insert initial data
BEGIN
    insert_initial_data;
END;
/